/**
 * trainRoute.ts — Runtime route computation for the train highlight feature.
 *
 * When a train is selected on the map, this module fetches its timetable from
 * the community EDR API, looks up pre-computed track geometries from
 * railData.json, and assembles a list of colored polyline segments to render
 * on the Leaflet map.
 *
 * Data flow:
 *   1. Train selected → getTrainRoute() is called (cached per train)
 *   2. fetchTimetable() fetches the train's stop list from the community EDR
 *      (simrail-edr.emeraldnetwork.xyz). Cached in memory per train number.
 *   3. computeRoute() resolves each stop name to coordinates from the
 *      gazetteer in railData.json. Stops without coordinates are skipped.
 *   4. The route is trimmed to the first and last "known" stations (stations
 *      that resolved AND validated against the wiki track data at generation
 *      time — in-game resolvable stations).
 *   5. For each consecutive pair of resolved stops, the pre-computed track
 *      geometry is looked up from railData.segments. Keys are SORTED pairs
 *      ("aNorm|bNorm" with a<b, direction-agnostic); the polyline is reversed
 *      when the train travels opposite to the key order. Both directions of
 *      a hop share one geometry, so out-and-back trains draw identical lines.
 *   6. Each segment may span both drivable and non-drivable sections (e.g. LK1
 *      has a non-drivable gap between Myszków and Rozprza). The segmentColors
 *      field stores boundary indices that split the segment into green (drivable),
 *      red (non-drivable), or grey (no wiki data) sub-segments.
 *   7. Adjacent sub-segments of the same color are merged for rendering
 *      efficiency. Because every station has ONE canonical track node (chosen
 *      once at generation time), consecutive segments chain exactly — no
 *      bridging needed. Missing segments are drawn as grey straight lines.
 *
 * railData.json format (generated by scripts/generate-rail-data.mjs):
 *   {
 *     knownStations: string[],                          // In-game resolvable stations (for route trimming)
 *     stations: { [name]: [lat, lon] },                // Gazetteer; canonical on-track coords
 *     segments: { [key]: string },                     // Encoded Polylines (key = sorted pair "a|b", a<b)
 *     segmentColors: { [key]: [number, number][] }     // Color boundaries: [[startIndex, colorCode], ...]
 *   }
 *
 * Color codes: 0 = green (drivable), 1 = red (non-drivable), 2 = grey (no wiki data)
 *
 * Caching:
 *   - timetableCache: Per-train timetable fetch results (Map<serverCode|trainNo, Promise>)
 *   - routeCache: Per-train computed route results (Map<serverCode|trainNo, Promise>)
 *   Both are module-level Maps that persist for the session. This means clicking
 *   the same train twice doesn't re-fetch or re-compute.
 */
import railDataJson from "../components/railData.json";

/** A [lat, lon] coordinate pair in decimal degrees. */
export type RoutePoint = [number, number];

/**
 * A colored polyline segment to render on the map.
 * - green: drivable track (available in SimRail)
 * - red: non-drivable track (exists in wiki but not playable)
 * - grey: no wiki track data available (straight line between stations)
 */
export interface ColoredSegment {
	color: "green" | "red" | "grey";
	points: RoutePoint[];
}

/**
 * The railData.json structure loaded at build time.
 * This file is generated by scripts/generate-rail-data.mjs and committed
 * to the repository. It contains all pre-computed route data so no runtime
 * A* routing or OSM fetching is needed.
 */
interface RailData {
	/** In-game resolvable station names (used for route trimming). */
	knownStations: string[];
	/**
	 * Station coordinate gazetteer: normalized name → [lat, lon].
	 * For stations that participate in routes, the coordinate is the
	 * canonical track node the generator snapped them to (on-track,
	 * near the station's middle).
	 */
	stations: Record<string, number[]>;
	/**
	 * Pre-computed track geometries, keyed by the SORTED pair of normalized
	 * station names ("a|b" with a<b, direction-agnostic) → Encoded Polyline
	 * in key order. Reverse the decoded points when traveling b→a.
	 */
	segments: Record<string, string>;
	/**
	 * Color boundaries per segment (same sorted key): [[startIndex, colorCode], ...]
	 * Each entry marks where a new color section begins (by point index into
	 * the decoded polyline, in key order). colorCode: 0=green, 1=red, 2=grey.
	 * Segments not in this map default to [[0, 0]] (all green).
	 */
	segmentColors: Record<string, [number, number][]>;
}

/** Maps color codes (0, 1, 2) to color names ("green", "red", "grey"). */
const COLOR_NAMES = ["green", "red", "grey"] as const;

const railData = railDataJson as unknown as RailData;

/** Set of normalized known station names, used for route trimming. */
const knownSet = new Set(railData.knownStations);

/** Community EDR API base URL for fetching train timetables. */
const EDR_TIMETABLE_URL = "https://simrail-edr.emeraldnetwork.xyz/train";

/**
 * Normalizes a station name for matching across data sources.
 * Applies Unicode NFC, trims whitespace, collapses internal spaces, lowercases.
 * This ensures "Warszawa Główna Towarowa" matches "Warszawa Główna Towarowa WOA"
 * via the fuzzy resolver in the generator (which stores both under their
 * respective normalized forms).
 */
function normalizeName(name: string): string {
	return name.normalize("NFC").trim().replace(/\s+/g, " ").toLowerCase();
}

/**
 * Decodes a Google Encoded Polyline string into an array of [lat, lon] points.
 *
 * The encoding uses delta encoding with zigzag-signed varints at 5 decimal
 * places (~1.1m precision). Each coordinate is split into 5-bit groups with
 * a continuation bit (0x20) and offset by 63 to avoid control characters.
 *
 * Format per coordinate:
 *   1. Read varint for latitude delta (zigzag-decoded)
 *   2. Add delta to running latitude
 *   3. Read varint for longitude delta (zigzag-decoded)
 *   4. Add delta to running longitude
 *   5. Divide by 1e5 to get decimal degrees
 */
function decodePolyline(str: string): RoutePoint[] {
	let idx = 0;
	let lat = 0;
	let lon = 0;
	const pts: RoutePoint[] = [];
	while (idx < str.length) {
		// Decode latitude delta (varint with continuation bit 0x20)
		let shift = 0;
		let result = 0;
		let byte;
		do {
			byte = str.charCodeAt(idx++) - 63;
			result |= (byte & 0x1f) << shift;
			shift += 5;
		} while (byte >= 0x20);
		// Zigzag decode: if LSB is 1, value is negative
		lat += result & 1 ? ~(result >> 1) : result >> 1;

		// Decode longitude delta (same varint format)
		shift = 0;
		result = 0;
		do {
			byte = str.charCodeAt(idx++) - 63;
			result |= (byte & 0x1f) << shift;
			shift += 5;
		} while (byte >= 0x20);
		lon += result & 1 ? ~(result >> 1) : result >> 1;

		pts.push([lat / 1e5, lon / 1e5]);
	}
	return pts;
}

/** A timetable stop as returned by the community EDR API. */
interface TimetableStop {
	nameOfPoint?: string;
	nameForPerson?: string;
	line?: number;
}

/**
 * Per-train timetable cache. Keyed by "serverCode|trainNo".
 * Stores Promises so concurrent calls for the same train share a single fetch.
 */
const timetableCache = new Map<string, Promise<TimetableStop[] | null>>();

/**
 * Fetches a train's timetable from the community EDR API.
 * Results are cached per train (serverCode + trainNo) for the session.
 * Returns null if the fetch fails or the train has no timetable.
 */
function fetchTimetable(
	serverCode: string,
	trainNo: string,
): Promise<TimetableStop[] | null> {
	const key = `${serverCode}|${trainNo}`;
	if (!timetableCache.has(key)) {
		timetableCache.set(
			key,
			fetch(`${EDR_TIMETABLE_URL}/${serverCode}/${trainNo}`)
				.then((r) => (r.ok ? r.json() : null))
				.catch(() => null),
		);
	}
	return timetableCache.get(key)!;
}

/**
 * A timetable stop resolved to a coordinate.
 * - coord: [lat, lon] from the railData stations gazetteer
 * - name: normalized station name (used as segment key component)
 * - isKnown: whether the station is in the knownStations set (playable area)
 */
interface ResolvedStop {
	coord: RoutePoint;
	name: string;
	isKnown: boolean;
}

/**
 * Per-train route cache. Keyed by "serverCode|trainNo".
 * Stores Promises so concurrent calls share a single computation.
 */
const routeCache = new Map<string, Promise<ColoredSegment[] | null>>();

/**
 * Gets the colored route segments for a train.
 * This is the main entry point called by the TrainRoute component.
 * Results are cached per train for the session.
 *
 * @param train - Object with ServerCode and TrainNoLocal
 * @returns Array of ColoredSegment (green/red/grey polylines), or null if no route
 */
export function getTrainRoute(train: {
	ServerCode: string;
	TrainNoLocal: string;
}): Promise<ColoredSegment[] | null> {
	const key = `${train.ServerCode}|${train.TrainNoLocal}`;
	if (!routeCache.has(key)) {
		routeCache.set(key, computeRoute(train));
	}
	return routeCache.get(key)!;
}

/**
 * Computes the colored route segments for a train.
 *
 * Algorithm:
 *   1. Fetch the train's timetable (stop list with line numbers).
 *   2. Resolve each stop name to coordinates from the gazetteer.
 *      Stops without coordinates (signal boxes, off-map stations) are skipped.
 *   3. Trim the route to the first and last "known" stations.
 *   4. For each consecutive pair of resolved stops:
 *      a. Look up the pre-computed track geometry by the sorted key pair,
 *         reversing the decoded points when traveling against key order.
 *      b. If no geometry exists, draw a grey straight line (no wiki data).
 *      c. Split the polyline at color boundaries (from segmentColors)
 *         into green/red/grey sub-segments, in travel order.
 *      d. Merge adjacent same-color sub-segments. Consecutive segments
 *         share exact endpoints (canonical station nodes), so merging
 *         is exact — no bridging needed.
 *
 * @param train - Object with ServerCode and TrainNoLocal
 * @returns Array of ColoredSegment, or null if the route can't be computed
 */
async function computeRoute(train: {
	ServerCode: string;
	TrainNoLocal: string;
}): Promise<ColoredSegment[] | null> {
	const stops = await fetchTimetable(train.ServerCode, train.TrainNoLocal);
	if (!stops || stops.length < 2) return null;

	// Resolve each stop to coordinates. Stops without coordinates are skipped.
	const resolved: ResolvedStop[] = [];
	for (const stop of stops) {
		const name = stop.nameOfPoint || stop.nameForPerson;
		if (!name) continue;
		const norm = normalizeName(name);
		const coordArr = railData.stations[norm];
		if (!coordArr) continue;
		resolved.push({
			coord: [coordArr[0], coordArr[1]],
			name: norm,
			isKnown: knownSet.has(norm),
		});
	}

	// Trim to the first and last known stations (playable area boundary).
	let first = -1;
	let last = -1;
	for (let i = 0; i < resolved.length; i++) {
		if (resolved[i].isKnown) {
			if (first < 0) first = i;
			last = i;
		}
	}
	if (first < 0 || last <= first) return null;

	const effective = resolved.slice(first, last + 1);
	if (effective.length < 2) return null;

	// Assemble colored segments from pre-computed data.
	const segments: ColoredSegment[] = [];
	let prevConnected = false;

	for (let i = 0; i < effective.length - 1; i++) {
		const a = effective[i];
		const b = effective[i + 1];

		// Segments are keyed by the sorted pair of names; reverse the decoded
		// points when the train travels against key order.
		const key = a.name < b.name ? `${a.name}|${b.name}` : `${b.name}|${a.name}`;
		const encoded = railData.segments[key];

		// No pre-computed route — draw a grey straight line to indicate
		// the route continues but track data is not available.
		if (!encoded) {
			segments.push({ color: "grey", points: [a.coord, b.coord] });
			prevConnected = false;
			continue;
		}

		const reversed = a.name > b.name;
		// Decode in KEY order — boundary indices refer to key-order points.
		// Travel direction is applied after slicing, by reversing the
		// sub-segments and their points below.
		const allPts = decodePolyline(encoded);

		// Get color boundaries: [[startIndex, colorCode], ...] in KEY order.
		// Default to [[0, 0]] (all green) if not in the data.
		const boundaries = railData.segmentColors?.[key] ?? [[0, 0]];

		// Split the polyline into colored sub-segments at each boundary
		// (in stored order), then reverse both the sub-segment order and
		// their points when traveling against key order.
		const subs: {
			color: "green" | "red" | "grey";
			points: RoutePoint[];
		}[] = [];
		for (let bi = 0; bi < boundaries.length; bi++) {
			const [startIdx, colorCode] = boundaries[bi];
			// End index is the start of the next boundary, or the end of the polyline.
			const endIdx =
				bi < boundaries.length - 1 ? boundaries[bi + 1][0] : allPts.length;
			// Slice includes the endIdx point for continuity with the next sub-segment.
			const subPts = allPts.slice(
				startIdx,
				bi < boundaries.length - 1 ? endIdx + 1 : endIdx,
			);
			subs.push({
				color: COLOR_NAMES[colorCode] ?? "grey",
				points: subPts,
			});
		}
		if (reversed) {
			subs.reverse();
			for (const sub of subs) sub.points.reverse();
		}

		for (const { color, points: subPts } of subs) {
			// Merge with the previous segment if same color and connected
			// (no gap). Consecutive segments share exact endpoints (canonical
			// station nodes), so the merge is exact.
			const lastSeg = segments[segments.length - 1];
			if (prevConnected && lastSeg && lastSeg.color === color) {
				lastSeg.points.push(...subPts.slice(1));
			} else {
				segments.push({ color, points: subPts });
			}
			prevConnected = true;
		}
	}

	return segments;
}
