import Head from 'next/head'
import Image from "next/image";
import { Container, Flex, Space } from '@mantine/core';
import { FeatureCard } from '../components/FeatureCard';
import { Footer } from '../components/Footer';

export default function Home() {



    return (<>
        <Head>
            <title>SimRail - Home</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <main >
            <Container style={{ marginTop: 50 }}>
                <Flex align="center" direction={"column"}>
                    <Image alt="SimRail logo" src={"/logos/logo-fr.png"} width={258} height={82} />
                    <Flex style={{ marginTop: 50 }} direction={"column"} gap={48}>
                        <FeatureCard name='Live Map' href='https://map.simrail.app' image='/features/map.png' />
                        <FeatureCard name='EDR' target="_blank" href='https://edr.simrail.fr' image='/features/edr.png' />
                        <FeatureCard name='SOON ' href='servers' disabled image='/features/blog.png' />
                    </Flex>
                    <Space h="xl" />
                    <Footer />
                </Flex>
            </Container>

        </main>
    </>)
}
